name: AWS Lambda Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: install pipenv, awscli
        run: |
          pip3 install pipenv
          pip3 install awscli

      - name: install packages
        run: |
          export PIPENV_VENV_IN_PROJECT=1                                      
          pipenv sync

      - name: make lambda.zip
        run: sh zip_lambda_function.sh

      - name: lambda update (DEV)
        if: contains(toJSON(github.ref), 'dev')
        run: |
          aws lambda update-function-code --function-name lambda-alexa-curry-udon-timer --zip-file fileb://lambda.zip

      - name: lambda update (STG)
        if: contains(toJSON(github.ref), 'main')
        run: |
          aws lambda update-function-code --function-name lambda-alexa-curry-udon-timer --zip-file fileb://lambda.zip --publish
